export interface Data {
    Title: string;
    Year: string,
    Rated: string,
    Released: string,
    Runtime: string,
    Genre: string,
    Director: string,
    Writer: string,
    Actors: string,
    Language: string,
    Country: string,
    Awards: string,
    Poster:string,
    Metascore: string,
    imdbRating: string,
    imdbVotes: string,
    imdbID: string,
    Type: string,
    Response: string,
    Images: string[],
}